FROM node:20-alpine

WORKDIR /app

# Kopiujemy pliki projektu
COPY src/package*.json ./
RUN npm install --legacy-peer-deps

COPY src/ .

RUN npm run build

CMD ["sh", "-c", "rm -rf /output/* && cp -r dist/. /output/"]